// <auto-generated />
using System;
using Manabu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Manabu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190918202217_db-quizquestionadditions")]
    partial class dbquizquestionadditions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Manabu.Models.AnswerKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("QuestionId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerKeys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ya",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "a",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "i",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "u",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "e",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "o",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "ka",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 8,
                            Name = "ki",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 9,
                            Name = "ku",
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 10,
                            Name = "ke",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 11,
                            Name = "ko",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 12,
                            Name = "ga",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 13,
                            Name = "gi",
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 14,
                            Name = "gu",
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 15,
                            Name = "ge",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 16,
                            Name = "go",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 17,
                            Name = "sa",
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 18,
                            Name = "shi",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 19,
                            Name = "su",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 20,
                            Name = "se",
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 21,
                            Name = "so",
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 22,
                            Name = "za",
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 23,
                            Name = "ji",
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 24,
                            Name = "zu",
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 25,
                            Name = "ze",
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 26,
                            Name = "zo",
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 27,
                            Name = "ta",
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 28,
                            Name = "chi",
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 29,
                            Name = "tsu",
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 30,
                            Name = "te",
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 31,
                            Name = "to",
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 32,
                            Name = "da",
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 33,
                            Name = "dji",
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 34,
                            Name = "dzu",
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 35,
                            Name = "de",
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 36,
                            Name = "do",
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 37,
                            Name = "na",
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 38,
                            Name = "ni",
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 39,
                            Name = "nu",
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 40,
                            Name = "ne",
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 41,
                            Name = "no",
                            QuestionId = 41
                        },
                        new
                        {
                            Id = 42,
                            Name = "ha",
                            QuestionId = 42
                        },
                        new
                        {
                            Id = 43,
                            Name = "hi",
                            QuestionId = 43
                        },
                        new
                        {
                            Id = 44,
                            Name = "fu",
                            QuestionId = 44
                        },
                        new
                        {
                            Id = 45,
                            Name = "he",
                            QuestionId = 45
                        },
                        new
                        {
                            Id = 46,
                            Name = "ho",
                            QuestionId = 46
                        },
                        new
                        {
                            Id = 47,
                            Name = "ba",
                            QuestionId = 47
                        },
                        new
                        {
                            Id = 48,
                            Name = "bi",
                            QuestionId = 48
                        },
                        new
                        {
                            Id = 49,
                            Name = "bu",
                            QuestionId = 49
                        },
                        new
                        {
                            Id = 50,
                            Name = "be",
                            QuestionId = 50
                        },
                        new
                        {
                            Id = 51,
                            Name = "bo",
                            QuestionId = 51
                        },
                        new
                        {
                            Id = 52,
                            Name = "pa",
                            QuestionId = 52
                        },
                        new
                        {
                            Id = 53,
                            Name = "pi",
                            QuestionId = 53
                        },
                        new
                        {
                            Id = 54,
                            Name = "pu",
                            QuestionId = 54
                        },
                        new
                        {
                            Id = 55,
                            Name = "pe",
                            QuestionId = 55
                        },
                        new
                        {
                            Id = 56,
                            Name = "po",
                            QuestionId = 56
                        },
                        new
                        {
                            Id = 57,
                            Name = "ma",
                            QuestionId = 57
                        },
                        new
                        {
                            Id = 58,
                            Name = "mi",
                            QuestionId = 58
                        },
                        new
                        {
                            Id = 59,
                            Name = "mu",
                            QuestionId = 59
                        },
                        new
                        {
                            Id = 60,
                            Name = "me",
                            QuestionId = 60
                        },
                        new
                        {
                            Id = 61,
                            Name = "mo",
                            QuestionId = 61
                        },
                        new
                        {
                            Id = 62,
                            Name = "yu",
                            QuestionId = 62
                        },
                        new
                        {
                            Id = 63,
                            Name = "yo",
                            QuestionId = 63
                        },
                        new
                        {
                            Id = 64,
                            Name = "ra",
                            QuestionId = 64
                        },
                        new
                        {
                            Id = 65,
                            Name = "ri",
                            QuestionId = 65
                        },
                        new
                        {
                            Id = 66,
                            Name = "ru",
                            QuestionId = 66
                        },
                        new
                        {
                            Id = 67,
                            Name = "re",
                            QuestionId = 67
                        },
                        new
                        {
                            Id = 68,
                            Name = "ro",
                            QuestionId = 68
                        },
                        new
                        {
                            Id = 69,
                            Name = "wa",
                            QuestionId = 69
                        },
                        new
                        {
                            Id = 70,
                            Name = "wo",
                            QuestionId = 70
                        },
                        new
                        {
                            Id = 71,
                            Name = "n",
                            QuestionId = 71
                        });
                });

            modelBuilder.Entity("Manabu.Models.FlashCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .IsRequired();

                    b.Property<string>("Question")
                        .IsRequired();

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FlashCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "ya",
                            Question = "や",
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        });
                });

            modelBuilder.Entity("Manabu.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "や"
                        },
                        new
                        {
                            Id = 2,
                            Name = "あ"
                        },
                        new
                        {
                            Id = 3,
                            Name = "い"
                        },
                        new
                        {
                            Id = 4,
                            Name = "う"
                        },
                        new
                        {
                            Id = 5,
                            Name = "え"
                        },
                        new
                        {
                            Id = 6,
                            Name = "お"
                        },
                        new
                        {
                            Id = 7,
                            Name = "か"
                        },
                        new
                        {
                            Id = 8,
                            Name = "き"
                        },
                        new
                        {
                            Id = 9,
                            Name = "く"
                        },
                        new
                        {
                            Id = 10,
                            Name = "け"
                        },
                        new
                        {
                            Id = 11,
                            Name = "こ"
                        },
                        new
                        {
                            Id = 12,
                            Name = "が"
                        },
                        new
                        {
                            Id = 13,
                            Name = "ぎ"
                        },
                        new
                        {
                            Id = 14,
                            Name = "ぐ"
                        },
                        new
                        {
                            Id = 15,
                            Name = "げ"
                        },
                        new
                        {
                            Id = 16,
                            Name = "ご"
                        },
                        new
                        {
                            Id = 17,
                            Name = "さ"
                        },
                        new
                        {
                            Id = 18,
                            Name = "し"
                        },
                        new
                        {
                            Id = 19,
                            Name = "す"
                        },
                        new
                        {
                            Id = 20,
                            Name = "せ"
                        },
                        new
                        {
                            Id = 21,
                            Name = "そ"
                        },
                        new
                        {
                            Id = 22,
                            Name = "ざ"
                        },
                        new
                        {
                            Id = 23,
                            Name = "じ"
                        },
                        new
                        {
                            Id = 24,
                            Name = "ず"
                        },
                        new
                        {
                            Id = 25,
                            Name = "ぜ"
                        },
                        new
                        {
                            Id = 26,
                            Name = "ぞ"
                        },
                        new
                        {
                            Id = 27,
                            Name = "た"
                        },
                        new
                        {
                            Id = 28,
                            Name = "ち"
                        },
                        new
                        {
                            Id = 29,
                            Name = "つ"
                        },
                        new
                        {
                            Id = 30,
                            Name = "て"
                        },
                        new
                        {
                            Id = 31,
                            Name = "と"
                        },
                        new
                        {
                            Id = 32,
                            Name = "だ"
                        },
                        new
                        {
                            Id = 33,
                            Name = "ぢ"
                        },
                        new
                        {
                            Id = 34,
                            Name = "づ"
                        },
                        new
                        {
                            Id = 35,
                            Name = "で"
                        },
                        new
                        {
                            Id = 36,
                            Name = "ど"
                        },
                        new
                        {
                            Id = 37,
                            Name = "な"
                        },
                        new
                        {
                            Id = 38,
                            Name = "に"
                        },
                        new
                        {
                            Id = 39,
                            Name = "ぬ"
                        },
                        new
                        {
                            Id = 40,
                            Name = "ね"
                        },
                        new
                        {
                            Id = 41,
                            Name = "の"
                        },
                        new
                        {
                            Id = 42,
                            Name = "は"
                        },
                        new
                        {
                            Id = 43,
                            Name = "ひ"
                        },
                        new
                        {
                            Id = 44,
                            Name = "ふ"
                        },
                        new
                        {
                            Id = 45,
                            Name = "へ"
                        },
                        new
                        {
                            Id = 46,
                            Name = "ほ"
                        },
                        new
                        {
                            Id = 47,
                            Name = "ば"
                        },
                        new
                        {
                            Id = 48,
                            Name = "び"
                        },
                        new
                        {
                            Id = 49,
                            Name = "ぶ"
                        },
                        new
                        {
                            Id = 50,
                            Name = "べ"
                        },
                        new
                        {
                            Id = 51,
                            Name = "ぼ"
                        },
                        new
                        {
                            Id = 52,
                            Name = "ぱ"
                        },
                        new
                        {
                            Id = 53,
                            Name = "ぴ"
                        },
                        new
                        {
                            Id = 54,
                            Name = "ぷ"
                        },
                        new
                        {
                            Id = 55,
                            Name = "ぺ"
                        },
                        new
                        {
                            Id = 56,
                            Name = "ぽ"
                        },
                        new
                        {
                            Id = 57,
                            Name = "ま"
                        },
                        new
                        {
                            Id = 58,
                            Name = "み"
                        },
                        new
                        {
                            Id = 59,
                            Name = "む"
                        },
                        new
                        {
                            Id = 60,
                            Name = "め"
                        },
                        new
                        {
                            Id = 61,
                            Name = "も"
                        },
                        new
                        {
                            Id = 62,
                            Name = "ゆ"
                        },
                        new
                        {
                            Id = 63,
                            Name = "よ"
                        },
                        new
                        {
                            Id = 64,
                            Name = "ら"
                        },
                        new
                        {
                            Id = 65,
                            Name = "り"
                        },
                        new
                        {
                            Id = 66,
                            Name = "る"
                        },
                        new
                        {
                            Id = 67,
                            Name = "れ"
                        },
                        new
                        {
                            Id = 68,
                            Name = "ろ"
                        },
                        new
                        {
                            Id = 69,
                            Name = "わ"
                        },
                        new
                        {
                            Id = 70,
                            Name = "を"
                        },
                        new
                        {
                            Id = 71,
                            Name = "ん"
                        });
                });

            modelBuilder.Entity("Manabu.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Quiz 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Quiz 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Quiz 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Quiz 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Quiz 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Quiz 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Quiz 7"
                        });
                });

            modelBuilder.Entity("Manabu.Models.QuizQuestions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("QuestionId");

                    b.Property<int>("QuizId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionId = 1,
                            QuizId = 1
                        },
                        new
                        {
                            Id = 2,
                            QuestionId = 2,
                            QuizId = 1
                        },
                        new
                        {
                            Id = 3,
                            QuestionId = 3,
                            QuizId = 1
                        },
                        new
                        {
                            Id = 4,
                            QuestionId = 4,
                            QuizId = 1
                        },
                        new
                        {
                            Id = 5,
                            QuestionId = 5,
                            QuizId = 1
                        },
                        new
                        {
                            Id = 6,
                            QuestionId = 6,
                            QuizId = 1
                        },
                        new
                        {
                            Id = 7,
                            QuestionId = 7,
                            QuizId = 1
                        },
                        new
                        {
                            Id = 8,
                            QuestionId = 8,
                            QuizId = 1
                        },
                        new
                        {
                            Id = 9,
                            QuestionId = 9,
                            QuizId = 1
                        },
                        new
                        {
                            Id = 10,
                            QuestionId = 10,
                            QuizId = 1
                        },
                        new
                        {
                            Id = 11,
                            QuestionId = 13,
                            QuizId = 2
                        },
                        new
                        {
                            Id = 12,
                            QuestionId = 14,
                            QuizId = 2
                        },
                        new
                        {
                            Id = 13,
                            QuestionId = 16,
                            QuizId = 2
                        },
                        new
                        {
                            Id = 14,
                            QuestionId = 20,
                            QuizId = 2
                        },
                        new
                        {
                            Id = 15,
                            QuestionId = 34,
                            QuizId = 2
                        },
                        new
                        {
                            Id = 16,
                            QuestionId = 35,
                            QuizId = 2
                        },
                        new
                        {
                            Id = 17,
                            QuestionId = 55,
                            QuizId = 2
                        },
                        new
                        {
                            Id = 18,
                            QuestionId = 56,
                            QuizId = 2
                        },
                        new
                        {
                            Id = 19,
                            QuestionId = 63,
                            QuizId = 2
                        },
                        new
                        {
                            Id = 20,
                            QuestionId = 68,
                            QuizId = 2
                        },
                        new
                        {
                            Id = 21,
                            QuestionId = 11,
                            QuizId = 3
                        },
                        new
                        {
                            Id = 22,
                            QuestionId = 29,
                            QuizId = 3
                        },
                        new
                        {
                            Id = 23,
                            QuestionId = 31,
                            QuizId = 3
                        },
                        new
                        {
                            Id = 24,
                            QuestionId = 36,
                            QuizId = 3
                        },
                        new
                        {
                            Id = 25,
                            QuestionId = 37,
                            QuizId = 3
                        },
                        new
                        {
                            Id = 26,
                            QuestionId = 44,
                            QuizId = 3
                        },
                        new
                        {
                            Id = 27,
                            QuestionId = 22,
                            QuizId = 3
                        },
                        new
                        {
                            Id = 28,
                            QuestionId = 28,
                            QuizId = 3
                        },
                        new
                        {
                            Id = 29,
                            QuestionId = 30,
                            QuizId = 3
                        },
                        new
                        {
                            Id = 30,
                            QuestionId = 33,
                            QuizId = 3
                        },
                        new
                        {
                            Id = 31,
                            QuestionId = 39,
                            QuizId = 4
                        },
                        new
                        {
                            Id = 32,
                            QuestionId = 48,
                            QuizId = 4
                        },
                        new
                        {
                            Id = 33,
                            QuestionId = 71,
                            QuizId = 4
                        },
                        new
                        {
                            Id = 34,
                            QuestionId = 26,
                            QuizId = 4
                        },
                        new
                        {
                            Id = 35,
                            QuestionId = 52,
                            QuizId = 4
                        },
                        new
                        {
                            Id = 36,
                            QuestionId = 58,
                            QuizId = 4
                        },
                        new
                        {
                            Id = 37,
                            QuestionId = 65,
                            QuizId = 4
                        },
                        new
                        {
                            Id = 38,
                            QuestionId = 70,
                            QuizId = 4
                        },
                        new
                        {
                            Id = 39,
                            QuestionId = 17,
                            QuizId = 4
                        },
                        new
                        {
                            Id = 40,
                            QuestionId = 19,
                            QuizId = 4
                        },
                        new
                        {
                            Id = 41,
                            QuestionId = 38,
                            QuizId = 5
                        },
                        new
                        {
                            Id = 42,
                            QuestionId = 51,
                            QuizId = 5
                        },
                        new
                        {
                            Id = 43,
                            QuestionId = 54,
                            QuizId = 5
                        },
                        new
                        {
                            Id = 44,
                            QuestionId = 67,
                            QuizId = 5
                        },
                        new
                        {
                            Id = 45,
                            QuestionId = 69,
                            QuizId = 5
                        },
                        new
                        {
                            Id = 46,
                            QuestionId = 50,
                            QuizId = 5
                        },
                        new
                        {
                            Id = 47,
                            QuestionId = 61,
                            QuizId = 5
                        },
                        new
                        {
                            Id = 48,
                            QuestionId = 64,
                            QuizId = 5
                        },
                        new
                        {
                            Id = 49,
                            QuestionId = 12,
                            QuizId = 5
                        },
                        new
                        {
                            Id = 50,
                            QuestionId = 43,
                            QuizId = 5
                        },
                        new
                        {
                            Id = 51,
                            QuestionId = 57,
                            QuizId = 6
                        },
                        new
                        {
                            Id = 52,
                            QuestionId = 59,
                            QuizId = 6
                        },
                        new
                        {
                            Id = 53,
                            QuestionId = 32,
                            QuizId = 6
                        },
                        new
                        {
                            Id = 54,
                            QuestionId = 21,
                            QuizId = 6
                        },
                        new
                        {
                            Id = 55,
                            QuestionId = 60,
                            QuizId = 6
                        },
                        new
                        {
                            Id = 56,
                            QuestionId = 40,
                            QuizId = 6
                        },
                        new
                        {
                            Id = 57,
                            QuestionId = 25,
                            QuizId = 6
                        },
                        new
                        {
                            Id = 58,
                            QuestionId = 23,
                            QuizId = 6
                        },
                        new
                        {
                            Id = 59,
                            QuestionId = 47,
                            QuizId = 6
                        },
                        new
                        {
                            Id = 60,
                            QuestionId = 53,
                            QuizId = 6
                        },
                        new
                        {
                            Id = 61,
                            QuestionId = 24,
                            QuizId = 7
                        },
                        new
                        {
                            Id = 62,
                            QuestionId = 15,
                            QuizId = 7
                        },
                        new
                        {
                            Id = 63,
                            QuestionId = 41,
                            QuizId = 7
                        },
                        new
                        {
                            Id = 64,
                            QuestionId = 66,
                            QuizId = 7
                        },
                        new
                        {
                            Id = 65,
                            QuestionId = 62,
                            QuizId = 7
                        },
                        new
                        {
                            Id = 66,
                            QuestionId = 46,
                            QuizId = 7
                        },
                        new
                        {
                            Id = 67,
                            QuestionId = 42,
                            QuizId = 7
                        },
                        new
                        {
                            Id = 68,
                            QuestionId = 45,
                            QuizId = 7
                        },
                        new
                        {
                            Id = 69,
                            QuestionId = 18,
                            QuizId = 7
                        },
                        new
                        {
                            Id = 70,
                            QuestionId = 49,
                            QuizId = 7
                        },
                        new
                        {
                            Id = 71,
                            QuestionId = 27,
                            QuizId = 7
                        });
                });

            modelBuilder.Entity("Manabu.Models.UserQuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnswerKeyId");

                    b.Property<int>("QuestionId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnswerKeyId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserQuestionAnswers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Manabu.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "00000000-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a862706e-b4fd-47d8-8bc2-66b3d4b7671d",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEzKN407uDeuH6VgCL4Nk+2r0SxrZUYLq9SMdtXR7CyhbHmubw9BKxO6WQAWyQdPEw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com",
                            FirstName = "admin",
                            LastName = "admin"
                        });
                });

            modelBuilder.Entity("Manabu.Models.AnswerKey", b =>
                {
                    b.HasOne("Manabu.Models.Question", "Question")
                        .WithMany("AnswerKeys")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Manabu.Models.FlashCard", b =>
                {
                    b.HasOne("Manabu.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Manabu.Models.QuizQuestions", b =>
                {
                    b.HasOne("Manabu.Models.Question", "Question")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Manabu.Models.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Manabu.Models.UserQuestionAnswer", b =>
                {
                    b.HasOne("Manabu.Models.AnswerKey", "AnswerKey")
                        .WithMany()
                        .HasForeignKey("AnswerKeyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Manabu.Models.Question", "Question")
                        .WithMany("UserQuestionAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Manabu.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
